import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import Themeprovider from "./_theme";
import Provader from "./_redux/Provader";
import ThemeSettings from '@/app/_components/settings'
import Nav from "./_components/nav";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provader>
          <AppRouterCacheProvider>
            <Themeprovider>
              <ThemeSettings>
                <Nav>
                  {children}
                </Nav>
              </ThemeSettings>
            </Themeprovider>
          </AppRouterCacheProvider>
        </Provader>
      </body>
    </html>
  );
}
